#!/bin/sh
#to install prerequisites for Python before installing it.
apt-get install build-essential checkinstall
apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev

#Download Python using following command from python official site

cd /usr/src
wget https://www.python.org/ftp/python/3.7.4/Python-3.7.4.tgz
tar xzf Python-3.7.4.tgz

#Compile Python Source
cd Python-3.7.4
./configure --enable-optimizations
make altinstall
python3.7 -V
